PROJECT: ASSOCIATIONS
balerum03/associations pull request #2
Opened 2020-10-27 21:26 UTC by bmuhamood

You want to build a site similar to a private Eventbrite which allows users to create events and then manage user signups. Users can create events and send invitations and parties (sound familiar?). Events take place at a specific date and at a location (which you can just store as a string, like “Andy’s House”).

A user can create events. A user can attend many events. An event can be attended by many users. This will require you to model many-to-many relationships and also to be very conscious about your foreign keys and class names (hint: you won’t be able to just rely on Rails’ defaults like you have before).

2020-10-28 04:50 UTC, trekab requested changes
### Changes Required! :recycle:
Hi team! Well done so far. There are some vital requirements that I'd like you to consider before moving forward though. These include:
- [ ] Add more descriptive instructions about setting up your project locally. The usual `bundle install`, `rails db:create`, and `rails db:migrate` and really helpful when it comes to instructing the user trying out your app locally.
- [x] __[Optional]__ Much as you have added a pull request summary, it appears that you directly copied and pasted text from the odin project without personalizing it. This makes the tense of your message wrong. Try to personalize this and think of the PR description as a summary of changes introduced by your commits to the project.
- [x] Navigation links should be present at the top of the page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/navigation_links_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations)). For most of your routes, I have to manually type them in my browser in order to access the resources. The navigation links should be able to guide the user.
- [x] The EventsController's `create` action should use the `build` method on association, i.e. `current_user.events.build(event_params)` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/build_method_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
- [x] The UsersController's `show` action should:
  - list events created by the user, i.e. `@created_events = current_user.events` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/current_user_show_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
  - list events previoulsy attendented by user **(Hint: use event model scope)**, i.e. `@past_events = current_user.attended_events.previous` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
  - list upcoming events previously attended by user **(Hint: use event model scope)**, i.e. `@upcoming_events = current_user.attended_events.upcoming` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
- [x] Add indexes for your database foreign keys ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/foreign_key_index_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/)). This is missing for the `creator_id` field on the `events` table.
- [x] Please add tests for your project using Rspec. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/unit_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[GitHub](https://github.com/trekab) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

2020-10-29 09:20 UTC, maelfosso requested changes
# Changes required 🔴 

Hello,

Thank you for the well-done job so far.
However, there are still some issues 

Kindly go through the comments left below, make the suggested changes and submit a new code review request
Thanks 

Mael FOSSO

2020-10-29 09:20 UTC, maelfosso commented on README.md
> +- Then run `rails db:migrate` no migrate the database.
We can't run `rails db:migrate` without running `rails db:create`
Kindly add it

2020-10-29 09:20 UTC, maelfosso commented on README.md
> +- Clone it using git.
Kindly give the command to run

2020-10-29 09:20 UTC, maelfosso commented on app/controllers/events_controller.rb
> +  end
The fact that there is no view for that action no redirection cause the app to download a kind of file.
Kindly redirect after a successful save. Redirect to the same page for example.

2020-10-29 09:20 UTC, maelfosso commented on app/views/users/show.html.erb
> +<h2> This are <%= @user.username %>'s events </h2>
It's not **This are** but `**These** are`

2020-10-29 09:20 UTC, maelfosso commented on app/views/events/show.html.erb
> +  <%= @attendees.where(event_id: @event.id).count %><br><br>
Such an expression must be done into a controller, not in the view.
Kindly remove it, please.

2020-10-29 09:20 UTC, maelfosso commented on app/views/events/show.html.erb
> +    <% @attendees.where(event_id: @event.id).each do |i|%>
Such an expression must be done into a controller, not in the view.
Kindly remove it, please.

2020-10-29 09:20 UTC, maelfosso commented on app/models/user.rb
> +  scope :today, -> { where('date == ?', Date.today) }
Used nowhere.
Kindly remove it, please.

2020-10-29 09:20 UTC, maelfosso commented on app/views/users/show.html.erb
> +<% @user.own_events.each do |e| %>
Create the view variables in the controller and use it here

2020-10-29 09:20 UTC, maelfosso commented on app/views/users/_attended.html.erb
> +  <% @user.events.previous.each do |event| %>
Create the view variables in the controller and use it here

2020-10-29 09:20 UTC, maelfosso commented on app/views/users/_attend_events.html.erb
> +  <% @user.events.upcoming.each do |event| %>
Create the view variables in the controller and use it here

2020-10-29 09:20 UTC, maelfosso commented on app/views/users/_today_events.html.erb
> +  <% @user.events.today.each do |event| %>
Create the view variables in the controller and use it here

2020-10-29 17:20 UTC, javitocor approved these changes
# STATUS APPROVED 🥇 🌟 

Congratulations team! 🥳 
You have met all the requirements and your project is approved! 💯 
Remember to fill up the completion form 📑  and you can move into the next project ⏩ 

Good luck 😃

2020-10-29 17:27 UTC, merged